FROM openjdk:21-jdk-slim

WORKDIR /app

COPY target/*.jar app.jar

EXPOSE 8080

ENV PORT=8080
ENV SPRING_PROFILES_ACTIVE=prod

CMD ["java", "-Dspring.profiles.active=prod", "-Dserver.port=8080", "-jar", "app.jar"] 