services:
  - type: web
    name: bloodline-adn-backend
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
    autoDeploy: true 