# Default Configuration
spring:
  application:
    name: Bloodline_ADN_System
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

jwt:
  secret: default-secret-key
  expiration: 86400000

logging:
  level:
    root: INFO
    com.example: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 