spring:
  application:
    name: Bloodline_ADN_System
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d1t364mr433s73eu9teg-a.oregon-postgres.render.com:5432/bloodlineadn}
    username: ${SPRING_DATASOURCE_USERNAME:bloodlineadn}
    password: ${SPRING_DATASOURCE_PASSWORD:FkInEJ1uW3pLLWG5nBqpreabd9g4iI94}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
  
  main:
    allow-bean-definition-overriding: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-your-256-bit-secret}
  expiration: 86400000

logging:
  level:
    root: INFO
    com.example: INFO
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 